### ISSUE TITLE
unknown field "user" in config metadata

### ISSUE THREAD

**Issue by vasyakrg** [k0smotron/k0smotron#894]
my config (see second metadata):

```yaml
apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: dev1
  namespace: dev1
spec:
  replicas: 1
  version: v1.31.3
  service:
      type: NodePort
      apiPort: 30443
      konnectivityPort: 30132
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: dev1
      user: dev1-admin
    spec:
      api:
...
```

but, in dev1-0 pod i have error:
`Error: failed to load node config: error unmarshaling JSON: while decoding JSON: json: unknown field "user"`

if i del `user: dev1-admin`, i have kubeconfig:

```
  name: k0s
contexts:
- context:
    cluster: k0s
    user: admin
  name: k0s
current-context: k0s
kind: Config
preferences: {}
users:
- name: admin
```

why `k0s` and `user: admin` ?

**Comment by makhov** [comment]
k0smotron creates Kubernetes clusters based on [k0s distribution](https://github.com/k0sproject/k0s)

`k0sConfig` field is used for [k0s config](https://docs.k0sproject.io/stable/configuration/), not for kubeconfig, and doesn't support `metadata.user` field.

**Comment by vasyakrg** [comment]
So there is no way I can get this data into it? 
Because I can transfer this data when I create the base cluster:

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-infra
  user: infra-admin
spec:
  k0s:
    version: v1.31.3+k0s.0
    dynamicConfig: false
    config:
      spec:
```
